var npcData = {
    main: [//primary npcs who give quests etc

    ],
    secondary: [//random encounters
        {name:'Dirty Angler',gender:'male'},
        {name:'Fish'},
        {name:'Combobulator',gender:'neuter'},
        {name:'Cobbler'},
        {name:'Peasant'},
        {name:'Landlord'},
        {name:'Milkmaid',gender:'female'},
        {name:'Wandering Salesman'},
        {name:'Skeevy Event Coordinator'},
        {name:'Knight',gender:'male'},
        {name:'Farmer',gender:'male'},
        {name:'Corrupt Banker'},
        {name:'Devious Crab'},
        {name:'Scarecrow',gender:'neuter'},
        {name:'Con Artist'},
        {name:'Wanderer'},
        {name:'Armored Worm'},
        {name:'Talking Mushroom',gender:'neuter'},
        {name:'Barnacle Crusted Seafarer',gender:'male'},
        {name:'Surgeon',gender:'male'},
        {name:'Tradesman',gender:'male'}
    ],
    traits: [
        //for a vs an, just test to see if string[0] is consonant or vowel
        "{npc} with a bowl on {ap} head",
        "{npc} with very long hair",
        "very nervous looking {npc}, who looks at you with mild distaste",
        "elderly {npc} with a large waist",
        "dirty {npc} with tattered clothing",
        "{npc} fidgeting with {ap} moneybag",
        "{npc} sobbing quietly to {po}self",
        "{npc} sauntering down the path with an air of hostility",
        "{npc} carefully counting a pouch of hidden goods",
        "{npc} who looks less than pleased to greet you",
        "{npc} covered from head to toe in homemade armors",
        "{npc} clutching {ap} sack of trinkets close to {po}self",
        "seemingly disatisfied {npc} approaching you slowly",
        "smiling {npc} with an unusual gait",
        "flea ridden {npc} with less than a full set of teeth",
        "blabbering {npc} hobbling around a corner",
        "{npc} talking to {po}self with a hushed whisper",
        "{npc} blabbing to {po}self incoherently",
        "hunched over {npc} leaning against {ap} staff",
        "{npc} burdened down with the cares of this world",
        "{npc} sitting on {ap} possessions hoarding them to {po}self",
        "{npc} searching for treasure in this barren world",
        "{npc} fussing about trivial matters",
        "{npc} in elegant garb",
        "disgruntled {npc}",
        "{npc} sitting on a {loc}",
        "{npc} laying in a {loc}",
        "{npc} beckoning you to approach {po} from a {loc}",
        "{npc} observing you from a {loc}",
        "{npc} mucking about next to a {loc}",
        "{npc} enjoying {po}self by a {loc}",
        "{npc} enjoying {po}self on a {loc}",
        "deceivingly friendly {npc} calling out to you by your first name"
    ]
};